- src/components/pip-minimized/pip-minimized.scss
- src/components/pip-minimized/pip-minimized.tsx
- src/components/pip/pip-child.tsx
- src/components/pip/pip.scss
- src/components/side-by-side/side-by-side.tsx
Current PR fixes bug with "hide" button that currently has absolute position and overlapped top bar when PIP component had top-right or top-left position.
The changes discussed with @RoyBregman: "hide" button use relative position and located "inside" draggable container (see on attached screenshots)
For screenshots background of **playkit-interactive-area** changed to **red**
> fix(FEV-933): fix "Hide button" location

- src/dualscreen.tsx
- src/global-types/kaltura-player/player.d.ts
primary ks should pass to secondary ks when loading media
solves FEV-970
> fix(FEV-970): changing a dual-screen entry to be Unlisted triggers an error on the player

- src/dualscreen.tsx
explicitly disable dualscreen plugin in the secondary.
Happens due changes in the KP which apply primary uiconf config on all players in the page.
Will be later replaced with some generic disable.
> fix(FEC-969): an error is displayed on the player console

- src/components/drag-and-snap-manager/drag-and-snap-manager.tsx
- src/components/pip/pip-child.tsx
- src/components/pip/pip.scss
- src/styles/_styles.scss
PR fixes issue with dragging area, when user can drag the child player by dragging buttons.
New property `draggableTarget` define which area should be listened on draggable events.
> fix(FEV-974): use draggable target to define draggable area

- src/components/responsive-manager/responsive-manager.tsx
- src/dualscreen.tsx
1) removed unnecessary `onMinSize` method for PIPMinimized and PIPMinimizedInverse layouts;
2) set default `onMinSize` property for ResponsiveManager component;
3) check player size on initial loading of ResponsiveManager component;
> fix(FEV-962): responsiveness - handle small size of player

- src/dualscreen-engine-decorator.ts
- src/dualscreen.tsx
- src/global-types/kaltura-player/engine-decorator.d.ts
- src/videoSyncManager.ts
1) On initial loading primary player wait till secondary player triggered `CHANGE_SOURCE_ENDED` event (ready hook);
2) On seek primary player wait till secondary player triggered `SEEKED` event (decorator);
> fix(FEV-1006): primary player wait for secondary player

- src/components/pip/pip.scss
- src/components/side-by-side/side-by-side.scss
small ie11 fix - when assigning position absolute - in ie11 needed to add left: 0 (other browsers have it by default)
> fix(FEV-1046): IE11 - Dual-screen plugin's layouts are broken

- src/dualscreen.tsx
Add flag to provider configuration to allow ignoring server config.
Related PRs:
- https://github.com/kaltura/kaltura-player-js/pull/480
- https://github.com/kaltura/playkit-js-providers/pull/153
Fixes FEC-11399.
> feat(FEC-11399): allow ignoring server config

- src/dualscreen.tsx
- src/image-sync-manager.ts
other cue points changes cause the entire active cues to be sent and handled.
Therefore we need to mark view changes we already handled in previous metadata updated event so we can ignore them
> fix(FEV-1107): changing layouts via player does not work

- src/dualscreen.tsx
When we are in the PIP inverse then pressing on SBS should change to SBS inverse
fixes FEV-1120
> fix(FEV-1120): parent and child screens cannot be switched on SBS layout

- src/dualscreen.tsx
- src/enums/layoutEnum.ts
- src/image-sync-manager.ts
1) use `_streamLayout` property to keep current stream layout;
2) reduce iterations thru `activeCuePoints` array;
3) use enums for stream layout changes;
> fix(FEV-1142): Returning to a wrong layout when using DVR for getting back to a "non-slides" point

- src/dualscreen.tsx
- src/providers/secondary-media-loader.ts
1) use KS from `player.cofig.session.ks` for getSecondaryMedia API call;
2) restore player if getSecondaryMedia API call failed;
> fix(FEV-1132):  Player breaks when there is no KS and dual plugin is configured

- README.md
Adding technical documentation about cue points service to existing dual-screen plugin documentation
> docs(FEV-1106): add cuepointsservice documentation

- src/dualscreen.tsx
- src/providers/secondary-media-loader.ts
**issue:**
potential of making an anonymous user to non-anonymous user when loadMedia is being executed of secondScreen.
**root cause:**
passing player.config.session.ks (non-anonymous ks).
**solution:**
passing player.config.session.ks only when isAnonymous is false.
Solves [FEV-1158](https://kaltura.atlassian.net/browse/FEV-1154)
Related to [FEC-11696](https://kaltura.atlassian.net/browse/FEC-11696)
> fix(FEV-1154): loadMedia for secondary screen transform anonymous user to non-anonymous

- src/image-sync-manager.ts
- test/src/image-sync-manager.spec.js
use `CuePoint` from `TIMED_METADATA_CHANGE` instead of `VttCue` from `TIMED_METADATA`
Depends on https://github.com/kaltura/kaltura-player-js/pull/512
> feat(FEC-11761): expose stream timed metadata - phase 2

- src/components/drag-and-snap-manager/drag-and-snap-manager.scss
fixed styles for "draaggbe-area" container to prevent style inheritance from KMS
> fix(FEV-1165): Child is displayed too low on the player - it's being cut by the progress bar

- src/dualscreen.tsx
apply player node in original element on layout change
> fix(FEV-1267): Navigating back in the scrubber to a point where dual screen is not triggered will cause the video to play with black screen 

- src/dualscreen.tsx
check if original Video Element exist
> fix(FEV-1295): Clicking on another entry in the playlist before the playlist start to play will make the playlist disappear

- README.md
- src/dualscreen.tsx
- src/types/DualScreenConfig.ts
From plugin config:
1) removed boolean property `inverse`;
2) added inverse layouts;
PS: update confluence page: https://kaltura.atlassian.net/wiki/spaces/PROD/pages/3121250849/Dual-Screen+Conf
> fix(FEV-1519): 'inverse' and 'layout' configuration is not clear and might be confused for users

- src/components/side-by-side/side-by-side.scss
- src/components/side-by-side/side-by-side.tsx
prevent apply SbS buttons over side-panels
> fix(FEV-1387): on dual screen with side by side layout when the kitchen sink is open the buttons of the dual screen are above the kitchen sink

- src/components/drag-and-snap-manager/drag-and-snap-manager.scss
**the issue:**
while dragging the pip player, the mouse cursor is currently changed to "move" icon (4 arrows)- it should be "hand" icon.
**solution:**
change the cursor value of dragging from "move" to "grabbing".
Solves [FEV-956](https://kaltura.atlassian.net/browse/FEV-956)
> fix(FEV-956): while dragging, the mouse cursor should be changed to 'hand' icon

- src/components/pip-minimized/pip-minimized.scss
- src/components/pip/pip-child.tsx
- src/image-player/image-player.scss
**Description of Changes:**
- pip screen should have an auto width, only the height should be calculated
- handle when pip is minimized- stretch the video/image to fill the player
Solves [FEV-1612](https://kaltura.atlassian.net/browse/FEV-1612)
> feat(FEV-1612): the ratio of the floating screen should fit the video itself

- src/image-sync-manager.ts
**the issue:**
image player is showing thumb cuepoints with subType=chapter; it should only display thumb cuepoints with subType=Slide.
**solution:**
validate that the cuepoint has subType=Slide before loading it.
Solves [FEV-1602](https://kaltura.atlassian.net/browse/FEV-1602)
> fix(FEV-1602): image player is displaying chapters

- src/components/pip/pip-child.tsx
- src/components/pip/pip.scss
**Description of the issue:**
following merging [PR](https://github.com/kaltura/playkit-js-dual-screen/pull/85), QA found that there is an issue in the behavior of the child player in Safari (works fine in Chrome).
seems like `width: auto` is not a good solution for Safari as it stretches the entire child container over the full width of the player.
**solution:**
I have rolled back the previous change of the width and applied `object-fit: cover` to the child player instead.
Related to [FEV-1612](https://kaltura.atlassian.net/browse/FEV-1612)
[FEV-1612]: https://kaltura.atlassian.net/browse/FEV-1612
> fix(FEV-1612): fix safari issue

- src/dualscreen.tsx
**the issue:**
promise of dualscreen is stuck in pending when SecondaryMediaLoader does not exist, which is causing the player to stuck in spinning.
**solution:**
resolve promise in case there is an issue with the SecondaryMediaLoader.
Solves [FEV-1638](https://kaltura.atlassian.net/browse/FEV-1638)
[FEV-1638]: https://kaltura.atlassian.net/browse/FEV-1638
> fix(FEV-1638): dualscreen plugin is causing the player to stuck on loading spinner

- src/components/pip/pip-child.tsx
- src/components/pip/pip.scss
- src/image-player/image-player.scss
**Description of Changes:**
- pip screen should have an auto width, only the height should be calculated
- handle when pip is minimized- stretch the video/image to fill the player
Solves [FEV-1612](https://kaltura.atlassian.net/browse/FEV-1612)
[FEV-1612]: https://kaltura.atlassian.net/browse/FEV-1612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FEV-1612): the ratio of the dualscreen should adjust to its content

- src/image-sync-manager.ts
filter out chapter cues on timedMetadataChanged
> fix(FEV-1616): When entry includes a chapter and below on the same time a slide, the slide doesn't shown in dual screen plugin

- src/dualscreen.tsx
remove plugin listeners if media doesn't have dual-screen
> fix(FEV-1647): Dual screen buttons are available for express recording preview after clicking reply button

- src/components/pip-minimized/pip-minimized.scss
handle pip minimized and tiny dualscreen for content (slides & videos) with bad ratio.
Solves [FEV-1646](https://kaltura.atlassian.net/browse/FEV-1646)
[FEV-1646]: https://kaltura.atlassian.net/browse/FEV-1646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FEV-1646): minimized dual screen with bad ratio content doesn't fill the entire container

- src/components/pip/pip-child.tsx
- src/components/pip/pip.scss
- src/dualscreen.tsx
**the issue:**
following a new change, where in pip mode the child player dimensions is dynamic according to the content ratio, in a case where the width is small (~less than 190px) the tooltip of the expand button is cut.
**solution:**
- add `max-width=100` in case the child player is in portrait mode
- support portrait mode also for video and not just for images- according to the video's width and height.
Solves [FEV-1649](https://kaltura.atlassian.net/browse/FEV-1649)
[FEV-1649]: https://kaltura.atlassian.net/browse/FEV-1649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FEV-1649): dualscreen expand button tooltip is cut if child player's width is small

- src/components/pip/pip-parent.tsx
- src/components/pip/pip.scss
> fix(FEV-1386): Navigation panel is rendered 'alongSide' when set to 'over' when dual-screen plugin is active

- src/components/pip/pip.scss
specify plugin styles for KMC page (KMS page styles add to all divs `margin: auto` rule that breaks button positions for dual-screen plugin)
> fix(FEV-1537): When playing an entry that includes dual screen in kmc the buttons position is wrong.

- src/dualscreen.tsx
enable kaltura-live plugin for child media
> fix(FEC-12968): If starting to stream live after simulive dual has ended the player will still play the simulive content in child container

- src/components/pip/pip-child.tsx
- src/components/side-by-side/side-by-side-wrapper.tsx
- src/components/side-by-side/side-by-side.tsx
- src/dualscreen.tsx
- src/enums/layoutEnum.ts
- translations/en.i18n.json
change the labels of the "switch screen" and "expand screen" buttons to be more informative according to primary/secondary screens
solves: FEC-12921
> fix(FEC-12921): [V7-Acc] [Dual Screen] Narrator Screen reader for windows

- cypress/e2e/dual-screen.cy.ts
- src/dualscreen.tsx
solves: https://kaltura.atlassian.net/browse/FEC-13224
There race condition in multiscreen component: if slide cues registered by cue-point manager after multiscreen component got rendered - image player doesn’t appears in multiscreen container.
> fix(FEC-13224): slide player missed on multiscreen

- src/components/side-by-side/side-by-side.scss
- src/components/side-by-side/side-by-side.tsx
soleves: [FEC-13260](https://kaltura.atlassian.net/browse/FEC-13260)
issue caused by video-element of primary player that disappears once player hide UI.
The same solution already implemented for PiP mode: 
https://github.com/kaltura/playkit-js-dual-screen/blob/master/src/components/pip/pip-child.tsx#L143-L145
https://github.com/kaltura/playkit-js-dual-screen/blob/master/src/components/pip/pip.scss#L23
[FEC-13260]: https://kaltura.atlassian.net/browse/FEC-13260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FEC-13260): Side by Side mode: player got paused if primary media moved to multiscreen menu

- src/video-sync-manager.ts
the issue:
on Safari when run dual screen the video is getting stuck all the time. 
solution:
add sync delay threshold for Safari only to reduce the number of times it change the second player rate
> fix(SUP-37810):V7 multi-source entries in Safari

- src/components/pip/pip-child.tsx
disabling the native picture-in-picture functionality of the browsers, for the dualscreen player.
Solves [FEC-13591](https://kaltura.atlassian.net/browse/FEC-13591)
[FEC-13591]: https://kaltura.atlassian.net/browse/FEC-13591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FEC-13591): disable browser native PiP for dualscreen player

- src/dualscreen.tsx
- src/events/events.ts
- src/events/index.ts
- src/index.ts
Add Events (used by kava analytics)
https://github.com/kaltura/playkit-js-kava/pull/156
> [DualScreen Plugin]: Add Events (used by kava analytics)

- src/dualscreen.tsx
Application events analytics reporting to kava | PIP is sent to kava dashboard after PIPInverse.
Application events analytics reporting to kava | Switch screen event isn't sent on single media.
> fix(FEC-13760): Application events analytics reporting to kava | PIP is sent to kava dashboard after PIPInverse.

- src/components/side-by-side/side-by-side.tsx
Adding aria-label on expand buttons in side by side mode
solves [ADA-1122](https://kaltura.atlassian.net/browse/ADA-1122)
[ADA-1122]: https://kaltura.atlassian.net/browse/ADA-1122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ADA-1122): Dual screen expand buttons are unlabelled

- src/components/pip/pip-child.tsx
- src/dualscreen.tsx
**Issue:** 
"Switch to secondary screen" doesn't change the label to "Switch to primary screen" even you have clicked already the secondary screen
**Solution:**
Change the layout value in the pip-chile after the translation string replacement.
Solves [ADA-1193](https://kaltura.atlassian.net/browse/ADA-1193)
[ADA-1193]: https://kaltura.atlassian.net/browse/ADA-1193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ADA-1193): Player - Switch to secondary screen label

- src/components/side-by-side/side-by-side.scss
Align z-index with https://github.com/kaltura/playkit-js-ui/pull/908
solves: https://kaltura.atlassian.net/browse/FEC-14055
> fix(FEC-14055): fix z-indexes for side panels

- src/components/pip/pip-child.tsx
- src/components/pip/pip-parent.tsx
- src/components/side-by-side/side-by-side.tsx
- src/dualscreen.tsx
issue:
on dual screen, at first time can click on PIP button and video changed to PIP, once changes the streams and change it back when click on PIP it not working anymore
fix was provided but qa found that PIP will also be enabled after click hide button
fix:
enable pip in the parent instead of in the child, also add disable for PIP in case click on side-by-side button.
solved [SUP-44191](https://kaltura.atlassian.net/browse/SUP-44191)
[SUP-44191]: https://kaltura.atlassian.net/browse/SUP-44191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SUP-44191):v7 player issues when using picture-in-picture

- src/dualscreen.tsx
Issue:
Quality is not changed in childe entries when it is changed in the parent entry.
**Fix:**
Add listener to videotrackchange and change the quality manually to all the other entries.
part of - https://github.com/kaltura/playkit-js/pull/793, https://github.com/kaltura/kaltura-player-js/pull/851
solves [SUP-38407](https://kaltura.atlassian.net/browse/SUP-38407)
[SUP-38407]: https://kaltura.atlassian.net/browse/SUP-38407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SUP-38407): [GaTech] [Multistream - V7 Player] Child entries not loading high quality flavor assets

- src/dualscreen.tsx
- Changed function 'set _layout' to function 'updateLayout'.
- Added a new boolean variable called 'userInteraction' with default value 'true'.
- The function 'updateLayout' gets 'userInteraction =  true' only in places where the user in fact clicked to change layout.
- Added a new boolean variable called 'userInteraction' with default value 'false' to functions '_addBindings' and '_getSecondaryMedia' that being called during every entry 'loadMeida'.
- Added a new boolean variable called 'userInteraction' with default value 'true' to the next functions:
'_setMode', '_setDefaultMode, '_switchToHidden', '_switchToPIP', '_switchToSingleMedia', '_switchToSideBySide'.
- Calling functions that update layout via 'reset' function with 'userInteraction = false' …
> fix(FEC-14031): DUAL_SCREEN_CHANGE_LAYOUT is being sent upon every entry change in playlist

- src/video-sync-manager.ts
**Issue:**
When get parsing error with No media found, the video stops and a black screen is appear.
In dual screen - the player presents an Error Overlay.
**Fix:**
Mimic the behavior in V2 player, stop the video with the error and not show a black screen while the other player keep's playing.
[solved] (https://kaltura.atlassian.net/browse/SUP-45743)
> fix(SUP-45743): Errors on playback for mulitstream

- package.json
- src/dualscreen.tsx
- Added a new boolean variable called 'userInteraction' with default value 'false' for all functions.
- Via OnClickEvent/byKeyboard event **userInteraction = true** default value.
- Updatet 'test:prepare' command on package.json to: 
**"test:prepare": "yarn run build && yes | cp -i ./dist/playkit-dual-screen.js ./cypress/public/plugin.js && yes | cp -i ./dist/playkit-dual-screen.js.map ./cypress/public/playkit-dual-screen.js.map"**
for better debugging usecases.
[FEC-14031](https://kaltura.atlassian.net/browse/FEC-14031)
[FEC-14031]: https://kaltura.atlassian.net/browse/FEC-14031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FEC-14031-DUAL_SCREEN_CHANGE_LAYOUT is being sent in wrong cases

- src/video-sync-manager.ts
**Issue:**
When parsing error occurs on the secondary entry, it makes the whole player to fail.
**Fix:**
Instead of sent to the main player a critical error, send it a recovery error, and not reset the secondary player.
solved https://kaltura.atlassian.net/browse/SUP-47737
This bug was already fixed for this ticket: https://kaltura.atlassian.net/browse/SUP-45743
but the problem is replicated again.
> fix(SUP-47737): something went wrong message for v7 player

- src/dualscreen.tsx
**Issue:** 
When changing configuration in kava plugin, config is changed only on primary player and not also in child player.
Fix:
Add kava plugin configuration from primary player on child players.
Solves [FEC-14575](https://kaltura.atlassian.net/browse/FEC-14575)
[FEC-14575]: https://kaltura.atlassian.net/browse/FEC-14575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FEC-14575): As client running multiple player on Dual screen plugin, I would like the non-primary players to inherit config from the primary
