kaltura/playkit-js-dual-screen

.github/workflows/semantic-pr-title.yml
enforce semantic release title linting
=> chore: add pull request title lint

src/dualscreen.tsx
Reset layout and pip-position on replay
=> fix(FEV-926): reset layout on replay

src/dualscreen.tsx, src/global-types/kaltura-player/kaltura-player.d.ts
Using changes done in https://github.com/kaltura/kaltura-player-js/pull/460
=> feat(FEC-885): remove settings button from ui

package-lock.json, package.json, src/components/pip-minimized/pip-minimized.tsx, src/components/pip/pip-child.tsx, src/components/side-by-side/side-by-side.tsx
Icon default changed to support older icons, pass viewBox explicit to make icon to works
=> fix(FEC-10835): update icon component in ui

src/videoSyncManager.ts
Sync secondary player when primary player on pause
=> fex(FEV-921): video sync on pause

src/components/pip-minimized/pip-minimized.scss, src/components/pip-minimized/pip-minimized.tsx, src/components/pip/pip-child.tsx, src/components/pip/pip-parent.tsx, src/components/pip/pip.scss, src/components/side-by-side/side-by-side-wrapper.tsx, src/components/side-by-side/side-by-side.scss, src/components/side-by-side/side-by-side.tsx, src/dualscreen.tsx, src/enums/layoutEnum.ts, src/index.ts, src/utils/index.ts
Note: This doesn't support useNativeTextTrack - In native text tracks the captions will "move" together with the primary media
=> feat(FEV-826): I as a user want to enable captions function in dual-screen plugin

src/components/side-by-side/side-by-side-wrapper.tsx, src/dualscreen.tsx
implement inverse mode for side-by-side layout
=> fix(FEV-1005): side by side inverse

src/dualscreen.tsx
Resolve "ready" promise if current entry ID doesn't have secondary media
=> fix(FEV-1065): resolve ready promise for non-dual medias

src/dualscreen.tsx, src/image-sync-manager.ts, test/src/image-player/image-player.spec.js, test/src/image-sync-manager.spec.js, test/src/utils/test-utils.js, test/src/video-sync-manager.spec.js
- image player unit tests;
- image-sync manager unit tests;
- video-sync-manager unit tests fix;
=> feat(FEV-1024): image-sync-manager and image player unit tests

src/dualscreen.tsx
=> fix(FEV-1016): CuePoint Manager - add QA script

src/dualscreen.tsx
removing test temp code and registering to new cue point service
solves FEV-993
=> feat(FEV-993): getting thumb cue points using cue point service

src/dualscreen-engine-decorator.ts, yarn.lock
activate decorator only if secondary entry is media, so decorator can handle SEEKED event from secondary player
=> fix(FEV-1103): incorrect live indicator color (state) appear when changing states between DVR to live

CHANGELOG.md, package.json, src/dualscreen.tsx
add z-index to subtitles on single-view layout
=> fix(FEV-1130): Captions disappear when child video is in hidden mode

src/providers/secondary-media-loader.ts
add live type of media to getSecondaryMedia API call
=> fix(FEV-1329): Add live entry in the filter for the dual-screen plugin

src/components/pip-minimized/pip-minimized.scss, src/components/pip/pip.scss, src/components/side-by-side/side-by-side.scss, src/dualscreen.tsx, src/image-player/image-player.tsx, src/image-sync-manager.ts, src/styles/_styles.scss, test/src/image-player/image-player.spec.js
1) updated image-preload logic;
2) show image player only if image loaded;
3) fix issue with applying external layout;
=> fix(FEV-1322): slides that were broadcasted prior to the archive will appear in the navigation

src/components/button/button.tsx
=> fix(FEV-1158): show/hide buttons focus issue fixed when narrator is turned on

src/components/button/button.tsx, src/enums/labels.ts, src/image-player/image-player.tsx, src/image-sync-manager.ts
=> fix(FEV-1439): a11y fixes

package.json, src/components/button/button.tsx, src/components/pip-minimized/pip-minimized.tsx, src/components/pip/pip-child.tsx, src/components/side-by-side/side-by-side.tsx, src/enums/index.ts, src/enums/labels.ts, src/image-player/image-player.tsx, translations/en.i18n.json, yarn.lock
1. Dual screen hide/show button should be read as "hide/show dual screen" and not just hide/show
2. Dual screen side by side button should be read as "side by side screens" button
=> fix(FEV-1590): Mac voice over issues

package.json, src/components/pip-minimized/pip-minimized.scss, src/components/pip/pip.scss, src/image-player/image-player.scss, src/styles/_styles.scss, src/styles/_variables.scss, yarn.lock
**description of changes:**
- use styles from playkit-js-ui repo
- migrate common styles to variables and use them
Solves [FEV-1575](https://kaltura.atlassian.net/browse/FEV-1575)
[FEV-1575]: https://kaltura.atlassian.net/browse/FEV-1575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FEV-1575): migrate style of plugin dual screen

src/components/pip-minimized/pip-minimized.scss, src/components/pip/pip.scss, src/image-player/image-player.scss
fix pip, pip-minimized and sbs ratio issues.
Solves [FEV-1645](https://kaltura.atlassian.net/browse/FEV-1645)
[FEV-1645]: https://kaltura.atlassian.net/browse/FEV-1645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FEV-1645): for vertical or bad ratio slides in side by side and in parent, the content is cut

src/dualscreen.tsx
=> fix(FEV-1377): render side-by-side view in the video interactive area

package.json, yarn.lock
=> chore: upd playkit-kaltura-cuepoints

src/dualscreen.tsx
solves https://kaltura.atlassian.net/browse/FEC-13156
Do not destroy the main player (only secondary dual-screen players)
=> fix(FEC-13156): Player will disappear when switching from live to simulive/ from simulive to live or from offline slate to live

src/image-player/image-player.tsx
add 'alt' attr to image player
solves: FEC-13234
=> fix(FEC-13234): Unlabelled image is shown on the child player

package.json, src/dualscreen.tsx, src/image-player/image-player.tsx, src/image-sync-manager.ts, src/types/DualScreenPlayers.ts
solves: https://kaltura.atlassian.net/browse/FEC-13017
1) add dual-screen api that allows get thumbnails for active dual-screen layout;
2) add time-line service as kaltura-dependency;
=> feat(FEC-13017): dual-screen thubmnails

src/components/pip/pip-child.tsx, src/dualscreen.tsx
Reverts kaltura/playkit-js-dual-screen#141
=> Revert "fix(ADA-1193): Player - Switch to secondary screen label"

package.json, src/components/multiscreen/multiscreen.tsx, yarn.lock
=> update common dependencies

package.json, src/components/pip/pip-child.tsx, src/dualscreen.tsx, yarn.lock
issue:
on dual screen, at first time can click on PIP button and video changed to PIP, once changes the streams and change it back when click on PIP it not working anymore
solution:
when change the stream, check if the primary stream is of type video so remove the disabledPip
solve [SUP-44191](https://kaltura.atlassian.net/browse/SUP-44191)
[SUP-44191]: https://kaltura.atlassian.net/browse/SUP-44191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(SUP-44191):v7 player issues when using picture-in-picture

src/components/pip/pip-parent.tsx, src/styles/global.scss
Reverts kaltura/playkit-js-dual-screen#150
=> Revert "fix(FEC-14080): Accessibility fix for the top bar and the bottom bar"

src/dualscreen.tsx
issue:
sometimes second stream doesn't get load and there is an error on screen
solution:
wait 1 second before try to change quality for second stream
solve [SUP-45297](https://kaltura.atlassian.net/browse/SUP-45297)
[SUP-45297]: https://kaltura.atlassian.net/browse/SUP-45297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(SUP-45297):[Nomura] - Intermittent playback error with dual screen videos

src/dualscreen.tsx
related PR https://github.com/kaltura/playkit-js-timeline/pull/45/files
=> fix(CR-152): use timeline manager API

cypress/e2e/dual-screen.cy.ts, src/dualscreen.tsx, src/events/events.ts
Implements requested change from https://kaltura.atlassian.net/browse/FEC-14011
=> fix(FEC-14011): Slide and CTA Analytics

src/components/multiscreen/multiscreen.tsx
This is solving https://kaltura.atlassian.net/browse/ADA-1736
=> fix(ADA-1736) - Tooltip strict position
